### ISSUE TITLE
Baseline Pilot Results

### ISSUE THREAD

**Issue by michael-butler1994** [huntallcott/PhoneAddiction#12]
I've created a few histograms that compare _perceived_ phone use and pickup data from the baseline survey to _actual_ use & pickup data from the baseline screenshots. I limit the sample to test subjects who completed the baseline screenshot form (n=36) and who recorded an actual average daily usage of more than 10 minutes (n =29). A user with less than 10 minutes of usage likely just updated their iphone to 12.0. For each graph, outliers were removed if they were outside the graph range. thanks @lenasong for taking a look at these. Let me know if you have any questions! @huntallcott I'll post some more baseline summary stats on Monday.

My thoughts: Most test subjects underestimate phone usage and pickups. Given the small sample size, I'm hesitant to draw further conclusions on the magnitude of underestimation or the difference between usage underestimation vs pickup underestimation. 

1. Actual vs Perceived Pickups
- Superimposed Histogram
![actualphonepickups perceivedphonepickups perday](https://user-images.githubusercontent.com/35438895/47528333-eedafb00-d872-11e8-8b08-22fe3959aa5e.png)

-Difference Histogram (plots the difference in perceived and actual use for each test subject)
![pickupdifference perceived-actual perday](https://user-images.githubusercontent.com/35438895/47528343-f39faf00-d872-11e8-8c38-92ace9f90a0e.png)

2. Actual vs. Perceived Use
-Superimposed Histogram
![actualphoneuse perceivedphoneuse perday](https://user-images.githubusercontent.com/35438895/47528357-fb5f5380-d872-11e8-9227-b9068c405168.png)

-Difference Histogram
![usedifference perceived-actual perday](https://user-images.githubusercontent.com/35438895/47528364-02866180-d873-11e8-8724-13e254e61bae.png)

**Comment by huntallcott** [comment]
Great. Thanks @michael-butler1994. These are interesting. Looking forward to seeing the further results as soon as you post them.
Tagging @gentzkow so he sees this as well.

**Comment by michael-butler1994** [comment]
@gentzkow @lenasong @huntallcott  I've attached a pdf with a few summary stats from the baseline survey. My sample includes Baseline Survey completes (n =42), a larger sample than Baseline Screenshot Form Completes (n=36) used for the analysis above. 

Apologies for the delay.  Please let me know if there are other baseline questions you'd like me to look at. Next, I'll post some stats from the midline and on attrition. If you'd like to check my do file, pull the 'michael' branch of the repo, and navigate to Code/Analysis/Pilot. 


[BaselineSummaryStats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2543949/BaselineSummaryStats.pdf)

**Comment by gentzkow** [comment]
Wow! If there was any doubt that people think they're using their phones too much / too mindlessly / without thinking this dispels it.

Makes you wonder if we shouldn't go after some even more aggressive commitment device options -- maybe something a la [stickk.com](http://www.stickk.com/)?

**Comment by huntallcott** [comment]
@michael-butler1994 thanks, I agree that this is very interesting. 
Looking forward to seeing the further analyses here.

A couple points of order that will help us work efficiently together. 
1. Can you use more descriptive branch names, e.g. pilot_analysis instead of "michael"?
2. On the master, can you structure the code and data exactly as in the SocialMediaEffects repo? In particular:
* Can you get rid of the Code folder and re-org the folders so that you're working in analysis/source and outputting to analysis/release? 
* Please store all data and intermediate files in dropbox/PhoneAddiction/Data, anonymizing first as needed.
* Please structure the MasterFile and SetGlobals.do as in SocialMediaEffects/analysis/source so that the following holds: if Matt, Lena, or I open up your pilot analysis files, we can immediately run your analysis from our computers.
* Please always use saveold instead of save.

These principles (with some fudging on the folder structure) are articulated in [Matt's RA guide](https://github.com/gslab-econ/ra-manual/wiki) and [my RA guide](https://github.com/huntallcott/lab/wiki/Overview). Sorry to not have sent those earlier!

Once you've done that, I'd love to look at the data myself as well!

**Comment by huntallcott** [comment]
@michael-butler1994 ,
Just checking in on this. You are still working through the pilot results, yes? I'm very interested to see them.

**Comment by michael-butler1994** [comment]
@huntallcott Yes, I'll have a bunch of results on Monday! Got backed up with pilot management, and time off.

**Comment by huntallcott** [comment]
Thanks @michael-butler1994, this is great.
Here's what I feel like I learned so far:
* Page 3-4: People think they overuse their phones, as @gentzkow already pointed out above.
* Page 5-8: People underestimate pickups (by 20%) and minutes daily usage at baseline (by 10%) -- so there is something, but not huge.
* Page 9: $20 completion payment may reduce attrition somewhat relative to $10.
* Page 10: Going from $20 to $30 per week seems to get a lot of people to be willing to reduce their social media usage
* Page 11: we probably could price discriminate when we incentivize people.

I agree with you on the additional analyses that would be important, and I would love to see those ASAP.
Thanks again!

**Comment by michael-butler1994** [comment]
@huntallcott @lenasong @gentzkow 

Here's a pdf with more results [10_25_pilot1_sum_stats.pdf](https://github.com/huntallcott/PhoneAddiction/files/2613487/10_25_pilot1_sum_stats.pdf)

I've added a few new tables related to Use by App category, the Baseline Exploratory questions, Completion Payments, and our Treatment Restrictions. I also made significant revisions to the Attrition table, and the Phone use and Pickups tables. Please let me know if you have any questions! I plan to look at the short answer questions next. 

I'm about to push my updated analysis and lyx file to the pilot1 branch of the repo. 

Thanks @lenasong for the lyx example!

**Comment by huntallcott** [comment]
Thanks @michael-butler1994, this is great. I have the following observations:
1. Minor: in future it’s helpful if you can order the results "mathematically" instead of alphabetically, e.g. (Agree, Neutral, Disagree) instead of (Agree, Disagree, Neutral).
2. Lots of people are using screen time already as of October, and those who don’t use it want to experiment with it. This makes me think that a descriptive study of how they use screen time will be very interesting, and we need to contend with the fact that people already have "soft commitment devices" as we consider the experimental design and model in #13. 
3. Looks like we did have some success at getting people to use their phones less in the treatment conditions (Table 16, 24), so that's a nice proof of concept.
Thanks again.

**Comment by huntallcott** [comment]
Thanks @michael-butler1994, this is great.
In the open answers, the main thing this makes me think about is whether anything other than a semi-hard commitment (i.e. a reminder or an app closing when you go over your desired time limit) will have much impact on people's usage. This definitely influences the experimental design discussion ...

**Comment by huntallcott** [comment]
This is great, and closing this issue unless there's more to do on pilot 1.
