### ISSUE TITLE
Pilot 2 Management

### ISSUE THREAD

**Issue by michael-butler1994** [huntallcott/PhoneAddiction#15]
@huntallcott @lenasong @gentzkow 

Opening this thread to discuss logistics/management of Pilot 2. American Chris's app should be ready Wed 12th, so I think we should send the Baseline on Thursday the 13th.  Here are a few things we should decide, ordered by urgency. 

1. **Before Recruitment Begins**
   - Payoff Structure, so we can advertise potential payments correctly. For the last survey we used: $50 for option B treatment success; $10 option A treatment; $2 guaranteed, or 1 in 50 shot for $50 for each Friend Referral; $10 or $20 Completion Payment; $5 for baseline completion payment) 
   - Time length of pilot - so people know how long of a commitment this will be
   - If we want to revise the ad at all. It was pretty effective for the first pilot. 
![screen shot 2018-12-06 at 8 24 17 pm](https://user-images.githubusercontent.com/35438895/49621816-186c6380-f995-11e8-990a-e47256ef8bd1.png)

 2. **Before Pilot Begins**
     - Consent Form - I can draft this. Can we use the original, plus a paragraph explaining exactly what data American Chris's app will collect? Not sure what legal stuff we need to worry about.
     - Baseline Survey Questions
     - Here's a [link](https://nyu.ca1.qualtrics.com/jfe/preview/SV_bdxuiQsF3ADqEjr?Q_SurveyVersionID=current&Q_CHL=preview) to the previous Baseline survey w/ consent form. 

 Any other urgent tasks I'm missing?

**Comment by huntallcott** [comment]
Thanks @michael-butler1994 ,
Let's do the same length as before, and same consent form. Let's not advertise a specific amount of incentives because we need to nail that down.
I'd like to modify the baseline survey --
1. Take out the qualitative/open answer/exploratory questions we had.
2. Change the incentive structure to be a price per hour of usage instead of a maximum time limit.
3. If we have time, it would be good to start to think about the SWB questions we want to use, but these are lower-priority. I suspect that it will be best to import questions from the Facebook study.

In terms of 2, @lenasong can you think about the best way to write this up in the pilot?
I think we want to:
* Experiment with say 2 different non-zero price levels: $5 and $10 per hour.
* Have a multiple price list that allows people to trade off the price + a fixed payment vs. a different fixed payment that varies from row to row.
I can think about this more too over the weekend, although I'm tied up most of today in meetings in DC.

Thanks for getting this going.

**Comment by michael-butler1994** [comment]
The recruitment form is live! I will post some numbers tomorrow on how the ad is doing.

**Comment by huntallcott** [comment]
@lenasong , many thanks.
I made some edits to the [experimental design doc](https://docs.google.com/document/d/1WH9EAjsdJhLjE0jzieUN4UgSiaR3ug8kdIgyjVhBfGw/edit). I think we generally want to follow the wording and check-screens of the payday lending survey here. I wrote in my opinions.
[Qualtrics Survey.pdf](https://github.com/huntallcott/PhoneAddiction/files/2668530/Qualtrics.Survey.pdf)

You'll see that I'm OK trying just one price level for simplicity in the pilot, let's say $10 per average hour. We could do some stated preference work to try to optimize that.

**Comment by gentzkow** [comment]
Thanks @lenasong. This looks great. I really like the steps of asking them hypotheticals then asking them to practice.

I was a bit confused by the Midline questions though. Have these not been updated? I would have thought we'd re-ask the price per hour choices in the midline instead of switching to fixed price.

**Comment by lenasong** [comment]
@huntallcott thanks for the edits! File's updated with the same questions for midline.

**Comment by huntallcott** [comment]
@lenasong great, thanks. 
I think a great next step would be to code this up into Qualtrics and we can see how it looks. One minor thing is that you might or might not choose to make the date a variable input instead of text, in case we delay the period until after Dec 21. Up to you.
Thanks again!

**Comment by lenasong** [comment]
@huntallcott the WTA is mostly coded; we are waiting for instructions from the Chrises to add in an app installation section. Will send you and @gentzkow the survey when it's ready - by latest tomorrow afternoon.

Recruitment is slow - we are at 28. Should we delay the baseline survey to this Saturday and just roll with whatever number we recruit by then? I'm going to remove the sophomore/junior requirement and @michael-butler1994 is adding a second ad this afternoon.

**Comment by huntallcott** [comment]
Great, thanks, and yes to starting Saturday.

**Comment by michael-butler1994** [comment]
@huntallcott @lenasong @gentzkow 
Here's the [latest draft](https://nyu.ca1.qualtrics.com/jfe/preview/SV_000zvpoxUNFLCId?Q_SurveyVersionID=current&Q_CHL=preview) of the Baseline survey on Qualtrics. Let us know if you have any feedback! We plan to send the survey out tomorrow, early afternoon. 

Note: this preview allows you to see all questions related to app installation and transcript uploading. When a user fills the survey out, they will only need to upload their transcript using one method, for example.

**Comment by huntallcott** [comment]
@michael-butler1994 this is great, thanks.
I have a few comments, see this doc, also stored in dropbox/PhoneAddiction/Meeting Notes/Hunt's comments 12-15-2018 on pilot.docx

[Hunt's comments 12-15-2018 on pilot.docx](https://github.com/huntallcott/PhoneAddiction/files/2682678/Hunt.s.comments.12-15-2018.on.pilot.docx)

**Comment by michael-butler1994** [comment]
@gentzkow @huntallcott @lenasong 

Quick update: the baseline was sent out yesterday, and we're waiting to see if participants have been able to set up the tracking apps correctly.

In other news, recruiting with Facebook ads was significantly less effective for the second pilot. In this pilot, we spent $572 to recruit only 35 participants. In the first pilot we spent $224 to recruit 73 participants. See below for more stats: 


  | Amount spent | Ad clicks | Survey Responses | Successful Recruits | $/Successful Recruit
-- | -- | -- | -- | -- | --
pilot2 | $572 | 209 | 95 | 37 | $15
pilot1 | $224 | 210 | 191 | 73 | $3

A few things to note:
 - Pilot2's ad was active for 7 days while Pilot1's ad was active for 4 days. 
 - In Pilot2, only half the folks who clicked the ad actually started the survey; in Pilot1, 90% of ad clickers started the survey. I'm not sure why this occurred. The ad and the first page of the survey had essentially the same text in both Pilots. The Pilot2 ad targeted android users while the Pilot1 ad targeted iPhone users.
 - Both recruiting forms filtered out around 60% of the people who started the survey

For the real study, we might consider different recruiting methods. Way back when I was in college (2 years ago), companies would hire students to advertise their products. So, we could hire a student at each college and pay them a $3 per successful recruit. It would be 5x cheaper compared to Pilot2 recruiting!

**Comment by lenasong** [comment]
@huntallcott @gentzkow @michael-butler1994 
I've started a draft of the midline survey to be sent out by end of this week. See here for a [preview](https://nyu.ca1.qualtrics.com/jfe/preview/SV_9FE1fT1yfcFOqgZ?Q_SurveyVersionID=current&Q_CHL=preview) that includes both treatment and control reveals. 

A few things to highlight that I'd love to get your feedback on:
- for treatment assignment: I'm thinking 50% control, 25% general phone use reduction and 25% social media reduction. (quick note: the social media treatment can be gamed more easily, by using the browser more and switching into a different user account on the phone. In the latter case the apps know to record the total time but cannot track which specific apps are used)
- the payment is based on reduction from 5 hours for now - do we want to change to reduction from this week's average?
- treatment is assigned based on the question that asks "option A: $10 fixed payment" vs. "option B with $10/hour". I picked this one to maximize the number of people under restriction while being different from the control group - let me know if you think we should do something different 
- the participants will see this week's total usage as part of the midline. How much "coaching" should we do beyond reporting this? We could, for example, tell them that "your actual usage is X and you would have made more money if you chose all fixed payments higher than 50-10X". We want to help people understand how much they are using their phone, but do we want to help them understand how they are time-inconsistent?
- timeline: midline this weekend and endline Jan 6 with payment based on these next two weeks
- a section is added with open questions to get feedback on the apps 

@michael-butler1994 take a look especially at the embedded data fields (e.g. treatment text) when you are creating the midline contact list. Please also incorporate the necessary fields for this week's usage results. Thanks for getting this together.

**Comment by huntallcott** [comment]
@lenasong @michael-butler1994 great and many thanks.
#### Your bullets in order
1. OK
2. Yes if possible. You will have those data?
3. Agreed, good choice.
4. I don't think we want coaching on time inconsistency for now, although cool idea to save for later. I would just focus on helping them to understand the mechanics of the payment and how their usage maps into their payment.
5. Great.
6. Great.

#### Additional thoughts from looking at the Qualtrics design
A. “Smartphone use” question block: didn’t we already ask these? I don’t think we need to ask again if we did.
B. Practice_result and WTA_reminder: You wrote: “With a price of $10 for every hour of average usage under 5 hours, you would have earned $ _______
You should have chosen all fixed payments that are higher than $_______”
 
That’s not technically right (and it’s leading!). (Not technically right due to risk aversion, demand for commitment, etc.)
I would say:
One option you were offered was $50 minus $10 for every hour of usage under 5 hours. If you had chosen that option on the question that the computer chose to the “question that counts,” you would have earned $X.”

C. I note that practice_result and WTA_reminder appear twice. I’m not 100% against that, but also it feels duplicative. Is there one place where it’s less important? And if so, could we take that place out?

D.. Also: let’s us this phrase, the “question that counts” when explaining how the MPL works, as needed.

E. Treated_reveal. 
I’d phrase it a bit differently to be clearer both on the mechanics and the treatment assignment.

Congratulations! You have been selected to the rewards program! You have been randomly chosen to be rewarded based on ${e://Field/TreatText} phone use. 

The computer randomly the question in the row 8 row to be the “question that counts” for you. In that row, you chose ${e://Field/TreatChoiceLetter}. Thus, [you are guaranteed to the fixed payment of $10.] [you will be paid $50 minus $10 for every hour …]

You will also receive payments of $20 at the end of the study for completion of all surveys and additional payments for invites of friends who also complete the study.


F. In the endline let’s keep asking these App Feedback questions and please add another one where we ask if they were able to game the app, reassuring them that this would not affect their payment.


Thanks again!

#### Other notes
I. Matt is in France starting today and will be slower giving feedback. Here and possibly for endline, I'd go ahead and run with this without counting on him to respond.
II. Happy holidays to both of you!!!!

**Comment by lenasong** [comment]
@gentzkow @huntallcott thanks and happy holidays to you too!!! 

We've paid the baseline completes (20 in total) and Michael is finalizing details of the midline.

**Comment by huntallcott** [comment]
@michael-butler1994 thanks for making this happen! Merry Christmas!!!

**Comment by lenasong** [comment]
@gentzkow @michael-butler1994 @huntallcott happy new year! 

Here's a draft of the [endline survey](https://nyu.ca1.qualtrics.com/jfe/preview/SV_eaIv1KoA5AjsSAB?Q_SurveyVersionID=current&Q_CHL=preview), with questions added about app comparison, antisocial blocking usage and gaming. Feel free to make any edits.

We have a call scheduled with AntiSocial Chris tonight to work out issues with data exporting so we could include usage results as part of the endline. @michael-butler1994 thanks for the hard work getting the data together!

**Comment by huntallcott** [comment]
@gentzkow if you see this I think your feedback would be great -- last chance to get survey responses/feedback from people in the pilot.

Here are some thoughts:
0. @lenasong @michael-butler1994, thanks much, you guys are great.

1. I’m confused about the structure. (Sorry to be out of the loop.) Does each person have only one $FieldApp? If so, how are they able to compare the usage counts on the two apps? If they have both, should you be asking more of these open-answer questions for BOTH apps they had?

2. In general I think we want to use this opportunity for more open-answer. Examples:
* *Why* did you feel like AntiSocial or Pennyworth was better?
* *What specifically* were the reasons why Pennyworth or AntiSocial gave a more accurate summary of your usage?
* I think we also want to ask them questions about how well they understood the MPL language, whether that was confusing or easy, and whether they understood what they were committing to when they made choices on the MPL.

Those are my main thoughts at the moment!

**Comment by michael-butler1994** [comment]
@huntallcott @lenasong @gentzkow  I made a few revisions to the Endline survey to address Hunt's feedback. Here's a [link](https://nyu.ca1.qualtrics.com/jfe/preview/SV_eaIv1KoA5AjsSAB?Q_SurveyVersionID=current&Q_CHL=preview) to a preview of the revised survey. The preview's survey flow assumes that we were chosen to reduce our phone usage and that we have been using Antisocial and Pennyworth. 

 1. @huntallcott 20% (~4 remaining people) of participants are being tracked by both apps. 
 2. I added a few open questions and multiple choice questions for more detailed app feedback and to test MPL language comprehension. 

Please let me know if you have any feedback!

**Comment by gentzkow** [comment]
Thanks @huntallcott @michael-butler1994. 

I took a quick look and I think the basic structure is fine. It feels a little long to me with lots of open-ended questions; if there are any questions that we care relatively less about, we might consider dropping them to improve response quality on others.

Personally, I felt like the number of questions about Pennyworth vs. Antisocial was overkill. We might have just one set of questions about each including a free response question about pros/cons and then a final screen asking which people like better. (Also, the question about Antisocial app blocking)

I also thought it was odd to have the broad "Do you have any feedback for us to improve?" question midway through the survey. This seemed redundant with the final open-ended question. I might drop it.

I wonder if we couldn't word "game or manipulate the usage output" a bit more carefully. Maybe "distort or manipulate the information you sent us about your phone usage"?

**Comment by michael-butler1994** [comment]
thank for the feedback @gentzkow 
I've reduced the number of open ended questions comparing the apps. Here's a[ link](https://nyu.ca1.qualtrics.com/jfe/preview/SV_eaIv1KoA5AjsSAB?Q_SurveyVersionID=current&Q_CHL=preview) to the current survey draft. 

Lena and I plan to send out the Endline tonight around 9pm ET. We'll confirm when it's live.

**Comment by gentzkow** [comment]
Great. Thanks!

>

**Comment by michael-butler1994** [comment]
@huntallcott @gentzkow @lenasong 
Endline is live! I'll start a "Pilot 2 Results" issue later this week.

**Comment by huntallcott** [comment]
@michael-butler1994 thanks for doing this. Am closing this issue unless there's more to do on Pilot 2?

**Comment by michael-butler1994** [comment]
Ok to close issue 15 (pilot 2 management). I plan to post a few more
results tomorrow on issue 16 (Pilot 2 Results).
