### ISSUE TITLE
Determine how to get transcripts

### ISSUE THREAD

**Issue by KellyBuckley** [huntallcott/PhoneAddiction#6]

**Comment by KellyBuckley** [comment]
@lenasong If you can create a list of the schools we're interested in I can start looking into transcripts

**Comment by KellyBuckley** [comment]
Given the difficulty of getting schools to answer this question, I don't have time to go through all 12 universities. @huntallcott does it seem important to get definitive answers from all 12 schools and if so should I pull in another RA to help?

**Comment by lenasong** [comment]
What I got from phone calls with NYU transcripts team is that there isn't one fixed form and some kind of consent to disclosure information would suffice. I already emailed them to double check and get this in writing.

**Comment by lenasong** [comment]
I reached out to NYU last week to get a written confirmation but they are now going back on their words and doing further checks. Will let you know when I hear back.

Seems like third-party request is something they are hesitant to do. @KellyBuckley would be good to get a sense of the situation at other places.

**Comment by KellyBuckley** [comment]
Talked with someone at the Northeastern transcript office who gave me the email of a specific person to contact. Sent her an email, will try another school if I don't hear anything.

**Comment by lenasong** [comment]
Here is the response I received from NYU:

> I would have to review the consent form before I can confirm is that would be sufficient however, we generally ask for a signed copy of our Transcript Request Form which can be found on our website: https://www.nyu.edu/students/student-information-and-resources/registration-records-and-graduation/transcripts-certifications-grades/transcripts.html
>  
> If you could provide the ID numbers and a copy of this form signed by each student, we would be happy to process the batch of transcripts for you.
 
This is the form being referred to: https://www.nyu.edu/registrar/transcript-form.html. Note that this form does not send the request directly to the registrar's office; it only generates the signature page which the student has to then email/mail. The registrar's office is saying that batch processing is possible if we obtain these signed forms.

So I see two options here:
-re-create this form and incorporate it into our survey
-ask students to fill out the survey directly on NYU website and email us separately a pdf confirmation with their signatures 

I see option 1 being easier for everyone but it requires us to collect more personal information (university ID, full name, DOB, college attended and years attended) as part of the survey. 

We also want to make our request form look as similar to the one on the website as possible, so @KellyBuckley we'll need to add this into our consent and explore electronic signature on qualtrics. 

@gentzkow @KellyBuckley @huntallcott Thoughts?

**Comment by huntallcott** [comment]
Thanks.
Both options seem good; I'd lean toward the second one.
Remind me: does the NYU transcript request cost money, and could we get a volume discount if we eventually asked for a few hundred?

**Comment by lenasong** [comment]
@huntallcott In the NYU case there is no cost for these requests. I double checked and they only offer mailing of physical copies of official transcripts (no third-party e-transcript option).

**Comment by lenasong** [comment]
Transcript requests at NYU can be sent directly to Paige Levesque at pel3@nyu.edu

**Comment by KellyBuckley** [comment]
Northeastern update -- I emailed the person again yesterday, and she actually responded that it might be possible to get the transcripts in bulk if we have consent forms. She said she'd call me today but haven't heard from her yet.

**Comment by lenasong** [comment]
I've confirmed the NYU can process transcripts request in batch with collected consent forms at any point in the future. 

How do we process these forms? When and where should we have them mailed? These need to be specified by our participants in the consent form. 

For the full experiment, we need to check whether schools in our sample allow similar third-party transcript request.

**Comment by KellyBuckley** [comment]
Finally had a conversation with the person at Northeastern. She confirmed that we can get up to 100 unofficial transcripts from there if we get signed consent forms and send them directly to her.

**Comment by huntallcott** [comment]
@KellyBuckley, thank you. And just to confirm, we can get these transcripts IN THE SPRING even if the signed consent forms were signed IN THE FALL? Just wanted to double check.
After this let's pause on this issue, as I think I'm satisfied that we have proof-of-concept.

**Comment by KellyBuckley** [comment]
@huntallcott I made it clear that there would be a gap between collecting the forms and getting the transcripts and she was ok with that. I can confirm specifically fall -> spring.

**Comment by lenasong** [comment]
@KellyBuckley what does the consent form look like? i.e. is it also an online form to be filled out or it requires printing and scanning by the student?

**Comment by KellyBuckley** [comment]
@lenasong she said we'd have to create our own consent form. I would get it approved by her before we send it out.

**Comment by huntallcott** [comment]
@gentzkow @lenasong @michael-butler1994,
I am pasting my correspondence with Caroline Hoxby below. Seems that the bottom line is that even if we could work out logistics, the NSC doesn't have coverage of enough schools for this to be worthwhile.
So I think we're back to two two options with transcripts:
1. Work with a smaller number of specific schools and coordinate with registrars as needed for post-dated transcript requests. This would require some additional legwork to coordinate; perhaps @gentzkow can supply a couple of undergrads?
2. Have transcript requests as part of a post-endline survey and pray for low attrition rate. This would come with various benefits that we discussed in the meeting, namely (i) recruiting might be easier because not limited to specific schools, (ii) lower possibility for word about gaming to spread, and (iii) no worries about spillovers in social networks that might be hard to model. 
Thoughts on these two options, and/or any third option that might solve our problems?



**

Dear Hunt and Matt,

The National Student Clearinghouse (NSC) does not have transcript-based grades from more than a small share of institutions.  For the majority of institutions, the NSC collects only units fulfilled (i.e. progress) and degree receipt.  So, you would have progress and degrees, but probably not grades--which would be likely to pick up finer changes in behavior.

If you did want to use NSC nonetheless, you could possibly talk to Doug Shapiro.  He is the most likely to be interested.  However, I am very doubtful that NSC will go along.  This is really not their thing, and they have data privacy agreements that are likely to be prohibitive. Let me clarify this.

You want to do an experiment.  That means contacting and intervening with students--i.e. actually proposing to change their behavior via incentives.  This requires a fairly high level of human subjects review.  Typically, in education, this is not something that you could do through the NSC because they have not negotiated such agreements with their data providers.  The NSC has no actual contact with students themselves.  (I am not ruling your idea to work with NSC out, but I would bet against it.)  

I am not aware of any experiment that has been facilitated by NSC in this way.  Usually, when NSC works with researchers, the researchers have negotiated data agreements with other parties that do have direct access to students.  Then, the NSC is just brought along, providing merely "archival" data and not--by itself--facilitating experiments or interventions.

I think that your current approach of working via university registrars is more likely to be viable.

Sorry to have bad news but I am probably saving you time by alerting you to the issues.

All good wishes,

CMH

January 25, 2019 10:16:55 PM CET Hunt Allcott <allcott@gmail.com> wrote:
Caroline-
Hi. I hope you are well, and if I recall correctly, you are in Italy this year?

I'm writing because Matt (cc'd) and I are urgently working to set up a field experiment where we will pay college kids to use their phones less. Ideally we could recruit kids from many different schools, and ideally we could have transcript-based grades as one outcome (among many). 

Our ideal would be to have our study participants fill out post-dated transcript requests as of our baseline survey, and then we would receive the transcripts at the end of this semester. We know we can arrange this with a couple of example schools' registrars, but it's a pain and we'd like to be able to recruit from a wide range of schools.

Do you see a way to do this, for example by working with the National Student Clearinghouse to collect transcript request forms from the students and then delay fulfilling them? If so, do you happen to know somebody at the Clearinghouse with whom we could speak about this?

I really appreciate any guidance you might have!!

Hope to see you this summer at NBER.

-Hunt

-- 
Hunt Allcott

https://sites.google.com/site/allcott/home



-- 
Sent with https://mailfence.com
Secure and private email





-------
Caroline M. Hoxby
Scott and Donya Bommer Professor of Economics
Stanford University
Senior Fellow of The Hoover Institution
Director, Economics of Education Program, National Bureau of Economic Research
contact:
Department of Economics, 579 Serra Mall, Stanford CA USA
assistant:  Samantha Pringnitz 
650-725-8872, spring1@stanford.edu

**Comment by lenasong** [comment]
We will measure academic performance via 1) self-reported current term GPA at baseline and endline 2) unofficial transcript upload at baseline and post-endline.
